# Generated by Django 4.1.7 on 2023-03-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="email",
        ),
        migrations.RemoveField(
            model_name="category",
            name="registration_date",
        ),
        migrations.RemoveField(
            model_name="category",
            name="surname",
        ),
    ]
